---------------------------------------------------------------------- update buildpackage to not update pkg-sourcelist with postfix tar ball when it gets updated.
Committing in .

Modified Files:
	buildpackage
----------------------------------------------------------------------

diff --git a/buildpackage b/buildpackage
--- a/buildpackage
+++ b/buildpackage
@@ -6,6 +6,22 @@
 #   repository
 #
 
+# only add the file if $add is blank
+function add_to_pkg_sourcelist {
+    local file=$1
+    local filelist=$2
+    local add=$3
+
+    if [ -z "${add}" ]; then
+        echo ${file} >> ${filelist} && \
+        sort < ${filelist} > ${filelist}.n && \
+            mv ${filelist}.n ${filelist} || {
+                echo "Failed to update ${filelist}!"
+                exit 1
+        }
+    fi
+}
+
 # Initialize.
 # By now, shells must have functions. Ultrix users must use sh5 or lose.
 
@@ -52,11 +68,17 @@ RPM=/usr/bin/rpmbuild
 }
 
 # download_if_necessary to srcdir base/file if not already there
+#
+# add_file:
+# leave blank unless you want to disable updating the filelist
+# for example with the postfix source tar ball
 
-download_if_necessary() {
+function download_if_necessary {
     local srcdir=$1
     local base=$2
     local file=$3
+    local add_file=$4
+
     echo -n "===> checking ${file} ..."
     if [ ! -f "${srcdir}/${file}" ]; then
         echo " not found"
@@ -64,12 +86,7 @@ download_if_necessary() {
         (
             cd ${srcdir} && \
             wget ${base}/${file} && \
-            echo ${file} >> ${pkgdir}/pkg-sourcelist && \
-            sort < ${pkgdir}/pkg-sourcelist > ${pkgdir}/pkg-sourcelist.n && \
-            mv ${pkgdir}/pkg-sourcelist.n ${pkgdir}/pkg-sourcelist || {
-                echo 'Failed!'
-                exit 1
-            }
+	    add_to_pkg_sourcelist ${file} ${pkgdir}/pkg-sourcelist ${add_file}
         )
     else
         echo " found"
@@ -135,7 +152,7 @@ EOF
 
 echo "===> checking for Postfix tar ball"
 
-download_if_necessary ${srcdir} ${base} ${file}
+download_if_necessary ${srcdir} ${base} ${file} NO_UPDATE_PKG_SOURCELIST
 
 # Look for the TLS patches
 #	Source9: ftp://ftp.aet.tu-cottbus.de/pub/postfix_tls/%{tls_version}.tar.gz  
