*** empty log message ***

diff --git a/postfix.spec.in b/postfix.spec.in
--- a/postfix.spec.in
+++ b/postfix.spec.in
@@ -1,5 +1,5 @@
 ##############################################################################
-# $Id: postfix.spec.in,v 2.27 2000/12/13 22:51:53 root Exp $
+# $Id: postfix.spec.in,v 2.28 2000/12/14 20:29:22 root Exp $
 #
 # Spec file for package postfix designed to be built on RedHat Linux.
 # Please send bugfixes and comments to the packager.
@@ -16,7 +16,7 @@ PreReq: /sbin/chkconfig
 Provides: MTA smtpd smtpdaemon
 Conflicts: sendmail
 Version: 20001212
-Release: 1
+Release: 2
 Packager: Simon J Mudd <sjmudd@pobox.com> but see description below
 Vendor: None -- see packager
 Distribution: Experimental
@@ -298,10 +298,11 @@ umask 022
 umask 022
 
 if [ "$1" = 0 ]; then
-    # stop postfix silently (if it's running)
+    # stop postfix silently if it's running
     %{daemon_directory}/master -t 2>/dev/null || {
-    echo "Stopping the Postfix mail system"
-    kill `sed 1q %{queue_directory}/pid/master.pid` }
+        echo "Stopping the Postfix mail system"
+        kill `sed 1q %{queue_directory}/pid/master.pid`
+    }
 
     /sbin/chkconfig --del postfix                    
 
@@ -326,15 +327,14 @@ if [ "$1" = 0 ]; then
         done
         # selectively remove the rest of the queue directory structure
         # first the ones which are easy
-        for dir in corrupt deferred incoming maildrop pid private public saved; do
-            ( cd $dir && find . -type f -exec rm {}\; )
-            test -d $dir && ( rmdir $dir || echo "unable to remove directory %{queue_directory}/$dir" )
+        for dir in corrupt deferred incoming maildrop pid private public saved \
+                   active bounce defer flush; do
+            # dangerous I know
+            test -d $dir && {
+                ( cd $dir && rm -rf * )
+                ( rmdir $dir || echo "unable to remove directory %{queue_directory}/$dir" )
+            }
         done
-        # second the rest
-        for dir in active bounce defer flush; do
-            ( cd $dir && rm -rf * ) # dangerous I know
-            test -d $dir && ( rmdir $dir || echo "unable to remove directory %{queue_directory}/$dir" )
-        done  
     }
 fi
 
@@ -343,13 +343,14 @@ fi
 if [ "$1" != 0 ]; then
     # restart postfix if it was running
     # -- need to fix this to stop during install and keep note of the state for use here ---
-    # stop postfix silently (if it's running)
+    # stop postfix silently if it's running
     %{daemon_directory}/master -t 2>/dev/null || {
-    echo "Stopping the Postfix mail system"
-    kill `sed 1q %{queue_directory}/pid/master.pid` 
-    sleep 2 # to give things time to stop
-    %{daemon_directory}/master &
-    echo "Restarting the Postfix mail system" }
+        echo "Stopping the Postfix mail system"
+        kill `sed 1q %{queue_directory}/pid/master.pid` 
+        sleep 2 # to give things time to stop
+        %{daemon_directory}/master &
+        echo "Restarting the Postfix mail system"
+    }
 fi
 
 %clean
@@ -452,6 +453,10 @@ rm -rf ${RPM_BUILD_ROOT}
 #	Bennett Todd <bet@mordor.net>
 
 %changelog
+* Thu Dec 13 2000 Simon Mudd <sjmudd@pobox.com>
+- snapshot-20001212-2, minor fixes
+  %{queue_directory} removal wasn't correct
+
 * Wed Dec 13 2000 Simon Mudd <sjmudd@pobox.com>
 - snapshot-20001212-1, several changes following comments from
   Daniel Roesen <droesen@entire-systems.com>
