merge 2.3 to head

diff --git a/postfix-get-distribution b/postfix-get-distribution
--- a/postfix-get-distribution
+++ b/postfix-get-distribution
@@ -1,73 +1,87 @@
 #!/bin/sh
 #
-# postfix-get-distribution - Simple script to determine the correct
+# postfix-get-distribution - script to determine the correct
 # distribution, in the form <distribution>-<major>.<minor>
 #
 # - there appears to be no clear way of doing this which is cross platform
 #   compatible between different rpm vendors
 #
-# With rh9 the return value of rpm -q redhat-release does not include a
-# minor version.  This is used in several places in make-postfix.spec so we
-# generate a minor version of 0 if necessary.
+# With rh9/rhel3 the return value of rpm -q redhat-release does
+# not include a minor version.  This is used in several places in
+# make-postfix.spec so we generate a minor version of 0 if necessary.
 #
 # Recognised distributions so far are:
-# - RedHat Linux
 # - RedHat Enterprise Linux
-# - Fedora
-# - YellowDog Linux
 # - Whitebox Linux (reports as RedHat Enterprise Linux for building)
 # - CentOS Linux (reports as RedHat Enterprise Linux for building)
+# - TaoLinux (reports as RedHat Enterprise Linux for building)
+# - RedHat Linux
+# - Fedora Core
+# - YellowDog Linux
 # - Mandrake Linux
 
-version=$(echo '$Revision: 1.12 $' | sed -e 's/^.*: //g' -e 's/ .*$//g')
+[ -n "$DEBUG" ] && set -x
+myversion=$(echo '$Revision: 1.13 $' | sed -e 's/^.*: //g' -e 's/ .*$//g')
 myname=$(basename $0)
 
 # Provide a usage message
-function usage () {
+usage () {
+	cat <<-EOF
+	$myname version $myversion
 
-cat <<EOF
-$myname version $version
+	Copyright (C) 2002-2006 - Simon J Mudd <sjmudd@pobox.com>
+	This program may be freely redistributed under the terms of the GNU GPL
 
-Copyright (C) 2002-2004 - Simon J Mudd <sjmudd@pobox.com>
-This program may be freely redistributed under the terms of the GNU GPL
+	Usage: $myname [--help] [--distribution] [--name] [--major] [--minor] [--full]
 
-Usage: $myname [--help] [--distribution] [--name] [--major] [--minor] [--full]
-
-Shows the distribution name or one of several different components:
---distribution	<name>-<major>.<minor>		[default behaviour]
---name		redhat, rhel, yellowdoy, ... (abbreviated format)
---major		major version (3, 5, 6, 7, 8)
---minor		minor version (0, ...) [ may have decimal values ]
---full		Redhat-Release-X.Y, Whitebox-Release-X.Y, ...
---debug		show all values
-EOF
+	Shows the distribution name or one of several different components:
+	--distribution  <name>-<major>.<minor>		[default behaviour]
+	--name          redhat, rhel, yellowdog, ... (abbreviated format)
+	--major         major version (3, 5, 6, 7, 8)
+	--minor         minor version (0, ...) [ may have decimal values ]
+	--full          Redhat-Release-X.Y, Whitebox-Release-X.Y, ...
+	--debug         show all values on separate lines in forma item=value
+	--distro-info   Show debug parameter values only,  not the ‘‘name=’’
+	                label that normally precedes the debug value.
+	EOF
 }
 
-# is the given rpm installed?
-function check_release {
-	local release=$1
+# is the given rpm installed? (e.g. 'redhat-release', 'fedora-release')
+# - return exit code 0 if it is
+# - for debugging we compare against ${debug_release}
+is_installed () {
+    local package=$1
 
-	if [ -n "$debug_release" ]; then
-		if [ "$debug_release" = "$release" ]; then
-			echo 0
-		else
-			echo 1
-		fi
-		return
-	fi
-	rpm -q ${release} >/dev/null 2>&1
-	echo $?
+    if [ -n "${debug_release}" ]; then
+        [ "${debug_release}" = "${package}" ]
+    else
+        rpm -q ${package} 2>&1 >/dev/null
+    fi
 }
 
-# get the full release version
-function get_release {
-	local release=$1
+# get the <distro>-release %{version}-%{release}
+# - for debugging we return ${debug_full_release}
+# Thus 'centos-release-4-3.2' -> '4-3.2'
+get_pkg_full () {
+    local pkg_name=$1
 
-	[ -n "$debug_fullrelease" ] && {
-		echo "$debug_fullrelease"
-		return
-	}
-	rpm -q ${release}
+    if [ -n "${debug_full_release}" ]; then
+        echo "${debug_full_release}"
+    else
+        # if you have installed the XXX-release rpm more than once
+        # this will ensure that only one of the instances is
+        # recognised.
+        rpm -q ${pkg_name} | tail -1
+    fi
+}
+
+# given the pkg_full (%{name}-%{version}-%{release}) return the %version
+# Thus '4-3.2' -> '4'
+get_pkg_version () {
+    local pkg_name=$1
+    local pkg_full=$2
+
+    echo "$pkg_full" | sed -e "s/^${pkg_name}-//" -e 's/-[^-]*$//'
 }
 
 info=distribution
@@ -79,6 +93,7 @@ if [ -n "$1" ]; then
     --minor)		info=minor;;
     --full)		info=full;;
     --debug)		info=debug;;
+    --distro-info)      info=params;;
     --help)		usage; exit 0;;
     *)			usage; exit 1;;
     esac
@@ -87,97 +102,140 @@ fi
 # default values
 full="unknown-release-?.?"
 name=unknown
-release=0.0
+version=0.0
 major=0
 minor=0
 #
-# Get release information (if possible)
+# Determine the distribution we are running on
 #
-if [ $(check_release redhat-release) = 0 ]; then
-    # We are using RHL <= 9 OR enterprise linux
+if is_installed redhat-release; then
+    # We are using RedHat Linux OR RedHat Enterprise Linux
     # redhat-release-3ES-1
     # redhat-release-3ES-7.2
     # redhat-release-2.9.5AS-7 (taroon beta)
     # redhat-release-9-3
     # redhat-release-8.0-8
+    # redhat-release-7.3-1
     # redhat-release-7.2-1
     # redhat-release-6.2-1
-    rpmname=redhat-release
-    full=`get_release ${rpmname}`
-    if [ -n "`echo $full | egrep '(ES|ES|AS|WS)'`" ];
-    then
+    pkg_name=redhat-release
+elif is_installed centos-release; then
+    # CentOS SHOULD behave like rhel, so we name it the same
+    # centos-release-4-3.2
+    pkg_name=centos-release
+elif is_installed whitebox-release; then
+    # whitebox-release-3.0-6_i386
+    # whitebox-release-4-2.WB2
+    # - whitebox SHOULD behave like rhel, so we name it the same
+    pkg_name=whitebox-release
+elif is_installed tao-release; then
+    # tao-release-1.0-TL16
+    # Tao-Linux SHOULD behave like rhel, so we name it the same
+    pkg_name=tao-release
+elif is_installed sl-release; then
+    # Warning: it has not been confirmed that this actually works.
+    pkg_name=sl-release
+elif is_installed fedora-release; then
+    pkg_name=fedora-release
+elif is_installed redhat-release-es; then
+    pkg_name=redhat-release-es
+elif is_installed redhat-release-as; then
+    pkg_name=redhat-release-as
+elif is_installed mandrake-release; then
+    pkg_name=mandrake-release
+elif is_installed yellowdog-release; then
+    pkg_name=yellowdog-release
+else
+    # give up if we can not proceed
+    echo "ERROR: $myname - unable to determine distribution, exiting"
+    exit 1
+fi
+
+# Get the full package version (uncleaned)
+full=$(get_pkg_full ${pkg_name})
+version=$(get_pkg_version ${pkg_name} "$full")
+
+# Tidy up the version information into something more usable.
+case $pkg_name in
+redhat-release)
+    if [ -n "$(echo "$full" | egrep '[EWA]S')" ]; then
         name=rhel
     else
         name=redhat
     fi
-    release=`echo $full | sed -e "s;^${rpmname}-;;" -e 's;-[0-9.]*$;;' \
-                                         -e 's;[EWA]S;;'`
-elif [ $(check_release whitebox-release) = 0 ]; then
-    # whitebox SHOULD behave like rhel
-    rpmname=whitebox-release
-    full=`get_release ${rpmname}`
-    name=rhel	# compatibility with RedHat Enterprise Linux
-    release=`echo $full | sed -e "s;^${rpmname}-;;" -e 's;-[0-9.a-z_]*$;;'`
-elif [ $(check_release centos-release) = 0 ]; then
-    # CentOS SHOULD behave like rhel
-    rpmname=centos-release
-    full=`get_release ${rpmname}`
-    name=rhel  # compatibility with RedHat Enterprise Linux
-    release=`rpm -q --queryformat='%{VERSION}' ${rpmname}`
-elif [ $(check_release fedora-release) = 0 ]; then
-    rpmname=fedora-release
-    full=`get_release ${rpmname}`
+    # trim off the ES/WS/AS stuff
+    version=$(echo "$version" | sed -e 's;[EWA]S;;')
+    ;;
+centos-release)
+    name=rhel
+    ;;
+whitebox-release)
+    name=rhel
+    ;;
+tao-release)
+    name=rhel
+    ;;
+sl-release)
+    name=rhel
+    ;;
+fedora-release)
     name=fedora
-    release=`echo $full | sed -e "s;^${rpmname}-;;" -e 's;-[0-9.]*$;;'`
-elif [ $(check_release redhat-release-es) = 0 ]; then
-    rpmname=redhat-release-es
-    full=`get_release ${rpmname}`
+    ;;
+redhat-release-es|redhat-release-as)
     name=rhel
-    release=`echo $full | sed -e "s;^${rpmname}-;;" -e 's;[A-Z]*-[0-9.]*$;;'`
-elif [ $(check_release redhat-release-as) = 0 ]; then
-    rpmname=redhat-release-as
-    full=`get_release ${rpmname}`
-    name=rhel
-    release=`echo $full | sed -e "s;^${rpmname}-;;" -e 's;[A-Z]*-[0-9.]*$;;'`
-elif [ $(check_release mandrake-release) = 0 ]; then
-    rpmname=mandrake-release
-    full=`get_release ${rpmname}`
+    version=$(echo "$version" | sed -e 's;[A-Z]$;;')
+    ;;
+mandrake-release)
     name=mandrake
-    release=`echo $full | sed -e "s;^${rpmname}-;;" -e 's;-[0-9.]*mdk$;;'`
-elif [ $(check_release yellowdog-release) = 0 ]; then
-    rpmname=yellowdog-release
-    full=`get_release ${rpmname}`
+    ;;
+yellowdog-release)
     name=yellowdog
-    release=`echo $full | sed -e "s;^${rpmname}-;;" -e 's;-[0-9.]*$;;'`
+    ;;
+*)
+esac
+
+# from version determine the major and minor parts
+if echo "$version" | grep -q '\.'; then
+    # there's one or more '.'s in release (e.g. 8.0 OR 2.9.5)
+    major=$(echo "$version" | sed -e 's;\.[0-9.]*$;;')
+    minor=$(echo "$version" | sed -e 's;^[0-9]*\.;;')
+else
+    # there's no '.' in release (e.g. 9)
+    major=$version
 fi
 
-# from release determine the major and minor versions
-echo $release | grep -q '\.' && {
-    # there's one or more '.'s in release (e.g. 8.0 OR 2.9.5)
-    major=`echo $release | sed -e 's;\.[0-9.]*$;;'`
-    minor=`echo $release | sed -e 's;^[0-9]*\.;;'`
-} || {
-    # there's no '.' in release (e.g. 9)
-    major=$release
-}
+# tao-release fix
+# - tao-linux 1.0 is equivalent to rhel-3.0 so adjust the version numbering
+#   accordingly.
+[ "$pkg_name" = "tao-release" -a "$major" = 1 ] && major=3
 
 case $info in
 distribution)
-    echo ${name}-${major}.${minor};;
+    echo "${name}-${major}.${minor}"
+    ;;
 name)
-    echo ${name};;
+    echo "${name}"
+    ;;
 major)
-    echo ${major};;
+    echo "${major}"
+    ;;
 minor)
-    echo ${minor};;
+    echo "${minor}"
+    ;;
 full)
-    echo ${full};;
+    echo "${full}"
+    ;;
 debug)
-    echo name=$name
-    echo release=$release
-    echo major=$major
-    echo minor=$minor
-    echo full=$full
+    echo "name=$name"
+    echo "release=$version"
+    echo "major=$major"
+    echo "minor=$minor"
+    echo "full=$full"
+    echo "rpm_name=$pkg_name"	# maintain rpm_name for backwards compatibility
+    ;;
+params)
+    # maintain the same order as the previous debug output
+    echo "$name $version $major $minor $full $pkg_name"
     ;;
 *)
     echo "Internal error info=$info" >&2
