*** empty log message ***

diff --git a/postfix.spec.in b/postfix.spec.in
--- a/postfix.spec.in
+++ b/postfix.spec.in
@@ -1,4 +1,4 @@
-# $Id: postfix.spec.in,v 2.304.4.32 2006/03/20 20:54:47 sjmudd Exp $
+# $Id: postfix.spec.in,v 2.304.4.33 2006/04/02 16:37:03 sjmudd Exp $
 #
 # File used to generate the distribution-specific postfix.spec file.
 # If you need to make changes to postfix.spec, make them to postfix.spec.in
@@ -95,7 +95,7 @@
 # If set to 1 if official version, 0 if snapshot
 %define official 1
 %define V_postfix 2.2.9
-%define rel 2__SUFFIX__
+%define rel 3__SUFFIX__
 %if %{official}
 %define V_tarball %{V_postfix}
 %define ftp_dir official
@@ -124,8 +124,9 @@
 %define mailq_path %{_bindir}/mailq.postfix
 %define rmail_path %{_bindir}/rmail.postfix
 %define sendmail_path %{_sbindir}/sendmail.postfix
+%define usrlib_sendmail %{_libdir}/sendmail.postfix
 
-%define init_directory /etc/rc.d/init.d
+%define initdir /etc/rc.d/init.d
 
 %define postfinger postfinger-1.29
 %define whinge /usr/bin/logger -p mail.info -t postfix/rpm
@@ -136,12 +137,12 @@ Group: System Environment/Daemons
 URL: http://www.postfix.org
 License: IBM Public License
 PreReq: chkconfig, initscripts, shadow-utils
-PreReq: /etc/init.d, /sbin/service
+PreReq: /etc/init.d, /sbin/service, chkconfig >= 1.3
 Epoch: 2
 
 Provides: MTA smtpd smtpdaemon
-Provides: %{_sbindir}/sendmail %{_bindir}/mailq %{_bindir}/newaliases
-Provides: %{_bindir}/rmail
+Provides: %{_sbindir}/sendmail %{_bindir}/mailq %{_bindir}/newaliases %{_bindir}/rmail
+Provides: %{_mandir}/man1/newaliases.1.%{mps} %{_mandir}/man5/newaliases.5.%{mps}
 
 Version: %{V_package}
 Release: %{rel}
@@ -261,7 +262,7 @@ The binary and source rpms I produce are currently available at
 and the mirrors which can be found at the following URL:
 	http://postfix.WL0.org/en/mirrors/
 
-This package/specfile was built from postfix.spec.in $Revision: 2.304.4.32 $.
+This package/specfile was built from postfix.spec.in $Revision: 2.304.4.33 $.
 To see the build options used to build this package see the file %{_sysconfdir}/postfix/postfix.spec.cf
 
 To use postfix with alternative options download the source package and
@@ -497,11 +498,11 @@ if [ $1 = 0 ]; then
         %whinge "- going to move it out of the way to %{_sysconfdir}/postfix.$timenow."
         mv %{_sysconfdir}/postfix %{_sysconfdir}/postfix.$timenow
     }
-    [ -d %{init_directory}/postfix ] && {
+    [ -d %{initdir}/postfix ] && {
         [ -n "$pretext" ] && %whinge "$pretext" && pretext=
-        %whinge "Detected a possible previous non-RPM startup script %{init_directory}/postfix."
-        %whinge "- going to move it out of the way to %{init_directory}/postfix.$timenow."
-        mv %{init_directory}/postfix %{init_directory}/postfix.$timenow
+        %whinge "Detected a possible previous non-RPM startup script %{initdir}/postfix."
+        %whinge "- going to move it out of the way to %{initdir}/postfix.$timenow."
+        mv %{initdir}/postfix %{initdir}/postfix.$timenow
     }
 fi
 
@@ -549,7 +550,15 @@ sh postfix-install -non-interactive \
        setgid_group=postdrop \
        html_directory=%{html_dir} \
        manpage_directory=%{_mandir} \
-       readme_directory=%{readme_dir} || exit 1 
+       readme_directory=%{readme_dir} || exit 1
+
+# To be compatible with later versions of RH sendmail/postfix packages
+# make /usr/lib/sendmail.postfix point to /usr/sbin/sendmail.postfix.
+# The alternatives then point /usr/lib/sendmail to /usr/lib/sendmail.postfix.
+# This *is* all a bit silly ...
+
+install -d -m755 $RPM_BUILD_ROOT%{_libdir}
+ln -sf ../sbin/sendmail.postfix $RPM_BUILD_ROOT%{usrlib_sendmail}
 
 # RPM compresses man pages automatically.  Edit postfix-files to avoid
 # confusing post-install.
@@ -567,9 +576,9 @@ bin/postconf -c ${RPM_BUILD_ROOT}%{_sysconfdir}/postfix -e \
 || exit 1
 
 # Install Sys V init script
-mkdir -p ${RPM_BUILD_ROOT}%{init_directory}
+mkdir -p ${RPM_BUILD_ROOT}%{initdir}
 install -c %{_sourcedir}/postfix-etc-init.d-postfix \
-                  ${RPM_BUILD_ROOT}%{init_directory}/postfix
+                  ${RPM_BUILD_ROOT}%{initdir}/postfix
 
 install -c auxiliary/rmail/rmail ${RPM_BUILD_ROOT}%{rmail_path}
 install -c auxiliary/qshape/qshape.pl ${RPM_BUILD_ROOT}/%{_sbindir}/qshape
@@ -798,41 +807,17 @@ fi
 
 [ "$1" = 1 ] || exit 0
 
-if [ -x %{_sbindir}/alternatives ]; then
-    %whinge "Fresh Postfix Install: using RH alternatives"
-    %{_sbindir}/alternatives --install %{_sbindir}/sendmail mta %{sendmail_path} %{with_alt_prio} \
-        --slave %{_bindir}/mailq mta-mailq %{mailq_path} \
-        --slave %{_bindir}/newaliases mta-newaliases %{newaliases_path} \
-        --slave %{_bindir}/rmail mta-rmail %{rmail_path} \
-        --slave %{_mandir}/man1/sendmail.1%{mps}   mta-sendmailman   %{_mandir}/man1/sendmail.postfix.1%{mps} \
-        --slave %{_mandir}/man1/mailq.1%{mps}      mta-mailqman      %{_mandir}/man1/mailq.postfix.1%{mps} \
-        --slave %{_mandir}/man1/newaliases.1%{mps} mta-newaliasesman %{_mandir}/man1/newaliases.postfix.1%{mps} \
-        --slave %{_mandir}/man5/aliases.5%{mps}    mta-aliasesman    %{_mandir}/man5/aliases.postfix.5%{mps} \
-        --initscript postfix
-else
-    if [ ! -e %{_sbindir}/sendmail ]; then
-        %whinge "Fresh Postfix Install, no %{_sbindir}/sendmail present: simulating RH alternatives"
-        ln -sf %{sendmail_path}             %{_sbindir}/sendmail
-        ln -sf %{mailq_path}                %{_bindir}/mailq 
-        ln -sf %{newaliases_path}           %{_bindir}/newaliases 
-        ln -sf %{rmail_path}                %{_bindir}/rmail 
-        ln -sf %{_mandir}/man1/sendmail.postfix.1%{mps}   %{_mandir}/man1/sendmail.1%{mps} 
-        ln -sf %{_mandir}/man1/mailq.postfix.1%{mps}      %{_mandir}/man1/mailq.1%{mps} 
-        ln -sf %{_mandir}/man1/newaliases.postfix.1%{mps} %{_mandir}/man1/newaliases.1%{mps} 
-        ln -sf %{_mandir}/man5/aliases.postfix.5%{mps}    %{_mandir}/man5/aliases.5%{mps}
-    fi
-fi
+%{_sbindir}/alternatives --install %{_sbindir}/sendmail mta %{sendmail_path} %{with_alt_prio} \
+    --slave %{_bindir}/mailq mta-mailq %{mailq_path} \
+    --slave %{_bindir}/newaliases mta-newaliases %{newaliases_path} \
+    --slave %{_bindir}/rmail mta-rmail %{rmail_path} \
+    --slave %{_libdir}/sendmail mta-sendmail %{usrlib_sendmail} \
+    --slave %{_mandir}/man1/sendmail.1%{mps}   mta-sendmailman   %{_mandir}/man1/sendmail.postfix.1%{mps} \
+    --slave %{_mandir}/man1/mailq.1%{mps}      mta-mailqman      %{_mandir}/man1/mailq.postfix.1%{mps} \
+    --slave %{_mandir}/man1/newaliases.1%{mps} mta-newaliasesman %{_mandir}/man1/newaliases.postfix.1%{mps} \
+    --slave %{_mandir}/man5/aliases.5%{mps}    mta-aliasesman    %{_mandir}/man5/aliases.postfix.5%{mps} \
+    --initscript postfix
 
-# Based on a request by Wietse:
-# Is /usr/lib/sendmail a regular file?
-# - if so AND it is NOT owned by an existing rpm link it to /usr/sbin/sendmail
-#   /usr/sbin/sendmail may be a binary or a link from alternatives to *ANY*
-#   mta package.
-#   [ don't use %sendmail_path which may "disappear" if the postfix rpm is removed. ]
-# if /usr/lib/sendmail IS owned by an rpm do NOT touch it.
-if test -f /usr/lib/sendmail; then
-    rpm -qf /usr/lib/sendmail >/dev/null 2>&1 || ln -sf /usr/sbin/sendmail /usr/lib/sendmail
-fi
 exit 0
 
 %triggerpostun -- sendmail
@@ -841,33 +826,17 @@ exit 0
 %whinge "%{V_postfix}-%{rel} triggerpostun -- sendmail: final number of sendmail packages=$2"
 [ $2 = 0 ] || exit 0
 
-if [ -x %{_sbindir}/alternatives ]; then
-    %whinge "%{V_postfix}-%{rel} Uninstalling sendmail, so setup Postfix: using RH alternatives"
-    %{_sbindir}/alternatives --install %{_sbindir}/sendmail mta %{sendmail_path} %{with_alt_prio} \
-        --slave %{_bindir}/mailq mta-mailq %{mailq_path} \
-        --slave %{_bindir}/newaliases mta-newaliases %{newaliases_path} \
-        --slave %{_bindir}/rmail mta-rmail %{rmail_path} \
-        --slave %{_mandir}/man1/sendmail.1%{mps}   mta-sendmailman   %{_mandir}/man1/sendmail.postfix.1%{mps} \
-        --slave %{_mandir}/man1/mailq.1%{mps}      mta-mailqman      %{_mandir}/man1/mailq.postfix.1%{mps} \
-        --slave %{_mandir}/man1/newaliases.1%{mps} mta-newaliasesman %{_mandir}/man1/newaliases.postfix.1%{mps} \
-        --slave %{_mandir}/man5/aliases.5%{mps}    mta-aliasesman    %{_mandir}/man5/aliases.postfix.5%{mps} \
-        --initscript postfix
-	:	# ensure the trigger exit status is 0
-else
-    if [ ! -e %{_sbindir}/sendmail ]; then
-        %whinge "%{V_postfix}-%{rel} Uninstalling sendmail, no %{_sbindir}/sendmail present: simulating RH alternatives"
-        ln -sf %{sendmail_path}             %{_sbindir}/sendmail
-        ln -sf %{mailq_path}                %{_bindir}/mailq 
-        ln -sf %{newaliases_path}           %{_bindir}/newaliases 
-        ln -sf %{rmail_path}                %{_bindir}/rmail 
-        ln -sf %{_mandir}/man1/sendmail.postfix.1%{mps}   %{_mandir}/man1/sendmail.1%{mps} 
-        ln -sf %{_mandir}/man1/mailq.postfix.1%{mps}      %{_mandir}/man1/mailq.1%{mps} 
-        ln -sf %{_mandir}/man1/newaliases.postfix.1%{mps} %{_mandir}/man1/newaliases.1%{mps} 
-        ln -sf %{_mandir}/man5/aliases.postfix.5%{mps}    %{_mandir}/man5/aliases.5%{mps}
-    else
-        :
-    fi
-fi
+%{_sbindir}/alternatives --install %{_sbindir}/sendmail mta %{sendmail_path} %{with_alt_prio} \
+    --slave %{_bindir}/mailq mta-mailq %{mailq_path} \
+    --slave %{_bindir}/newaliases mta-newaliases %{newaliases_path} \
+    --slave %{_bindir}/rmail mta-rmail %{rmail_path} \
+    --slave %{_libdir}/sendmail mta-sendmail %{usrlib_sendmail} \
+    --slave %{_mandir}/man1/sendmail.1%{mps}   mta-sendmailman   %{_mandir}/man1/sendmail.postfix.1%{mps} \
+    --slave %{_mandir}/man1/mailq.1%{mps}      mta-mailqman      %{_mandir}/man1/mailq.postfix.1%{mps} \
+    --slave %{_mandir}/man1/newaliases.1%{mps} mta-newaliasesman %{_mandir}/man1/newaliases.postfix.1%{mps} \
+    --slave %{_mandir}/man5/aliases.5%{mps}    mta-aliasesman    %{_mandir}/man5/aliases.postfix.5%{mps} \
+    --initscript postfix
+exit 0	# ensure the trigger exit status is 0
 
 %triggerpostun -- postfix
 
@@ -877,33 +846,17 @@ fi
 %whinge "%{V_postfix}-%{rel} triggerpostun -- postfix: final number of Postfix packages=$2"
 [ $2 -gt 0 ] || exit 0
 
-if [ -x %{_sbindir}/alternatives ]; then
-    %whinge "%{V_postfix}-%{rel} Upgrading Postfix: using RH alternatives"
-    %{_sbindir}/alternatives --install %{_sbindir}/sendmail mta %{sendmail_path} %{with_alt_prio} \
-        --slave %{_bindir}/mailq mta-mailq %{mailq_path} \
-        --slave %{_bindir}/newaliases mta-newaliases %{newaliases_path} \
-        --slave %{_bindir}/rmail mta-rmail %{rmail_path} \
-        --slave %{_mandir}/man1/sendmail.1%{mps}   mta-sendmailman   %{_mandir}/man1/sendmail.postfix.1%{mps} \
-        --slave %{_mandir}/man1/mailq.1%{mps}      mta-mailqman      %{_mandir}/man1/mailq.postfix.1%{mps} \
-        --slave %{_mandir}/man1/newaliases.1%{mps} mta-newaliasesman %{_mandir}/man1/newaliases.postfix.1%{mps} \
-        --slave %{_mandir}/man5/aliases.5%{mps}    mta-aliasesman    %{_mandir}/man5/aliases.postfix.5%{mps} \
-        --initscript postfix
-	:	# ensure the trigger exit status is 0
-else
-    if [ ! -e %{_sbindir}/sendmail ]; then
-        %whinge "%{V_postfix}-%{rel} Upgrading Postfix, no %{_sbindir}/sendmail present: simulating RH alternatives"
-        ln -sf %{sendmail_path}                           %{_sbindir}/sendmail
-        ln -sf %{mailq_path}                              %{_bindir}/mailq 
-        ln -sf %{newaliases_path}                         %{_bindir}/newaliases 
-        ln -sf %{rmail_path}                              %{_bindir}/rmail 
-        ln -sf %{_mandir}/man1/sendmail.postfix.1%{mps}   %{_mandir}/man1/sendmail.1%{mps} 
-        ln -sf %{_mandir}/man1/mailq.postfix.1%{mps}      %{_mandir}/man1/mailq.1%{mps} 
-        ln -sf %{_mandir}/man1/newaliases.postfix.1%{mps} %{_mandir}/man1/newaliases.1%{mps} 
-        ln -sf %{_mandir}/man5/aliases.postfix.5%{mps}    %{_mandir}/man5/aliases.5%{mps}
-    else
-        :
-    fi
-fi
+%{_sbindir}/alternatives --install %{_sbindir}/sendmail mta %{sendmail_path} %{with_alt_prio} \
+    --slave %{_bindir}/mailq mta-mailq %{mailq_path} \
+    --slave %{_bindir}/newaliases mta-newaliases %{newaliases_path} \
+    --slave %{_bindir}/rmail mta-rmail %{rmail_path} \
+    --slave %{_libdir}/sendmail mta-sendmail %{usrlib_sendmail} \
+    --slave %{_mandir}/man1/sendmail.1%{mps}   mta-sendmailman   %{_mandir}/man1/sendmail.postfix.1%{mps} \
+    --slave %{_mandir}/man1/mailq.1%{mps}      mta-mailqman      %{_mandir}/man1/mailq.postfix.1%{mps} \
+    --slave %{_mandir}/man1/newaliases.1%{mps} mta-newaliasesman %{_mandir}/man1/newaliases.postfix.1%{mps} \
+    --slave %{_mandir}/man5/aliases.5%{mps}    mta-aliasesman    %{_mandir}/man5/aliases.postfix.5%{mps} \
+    --initscript postfix
+exit 0	# ensure the trigger exit status is 0
 
 %preun
 umask 022
@@ -948,44 +901,29 @@ queue_directory_remove () {
 # /etc/postfix/postfix-chroot.sh disable
 # just to make sure, but won't do this yet. (If you think I should let
 # me know).
-[ "$1" = 0 ] && {
+if [ "$1" = 0 ]; then
     service postfix stop >/dev/null 2>&1
     chkconfig --del postfix
 
-    if [ -x %{_sbindir}/alternatives ]; then
-        %{_sbindir}/alternatives --remove mta %{sendmail_path}
-    elif [ -L %{_sbindir}/sendmail} ]; then
-        # check that symbolic link belongs to postfix
-        if [ $(ls -l %{_sbindir}/sendmail | awk '{print $11}') = %{sendmail_path} ]; then
-            # remove files
-            rm -f %{_sbindir}/sendmail
-            rm -f %{_bindir}/mailq
-            rm -f %{_bindir}/newaliases
-            rm -f %{_bindir}/rmail
-            rm -f %{_mandir}/man1/sendmail.1%{mps}
-            rm -f %{_mandir}/man1/mailq.1%{mps}
-            rm -f %{_mandir}/man1/newaliases.1%{mps}
-            rm -f %{_mandir}/man5/aliases.5%{mps}
-        fi
-    fi
+    %{_sbindir}/alternatives --remove mta %{sendmail_path}
 
     # userdel also deletes the user's group
     %{_sbindir}/userdel postfix   || %whinge "WARNING: failed to remove user postfix"
     %{_sbindir}/groupdel postdrop || %whinge "WARNING: failed to remove group postdrop"
 
-    cd %{_var}/spool/postfix && {
-        queue_directory_remove || :
-    } || :
-} || :
+    cd %{_var}/spool/postfix && queue_directory_remove
+fi
+
+exit 0
 
 %postun
 umask 022
 if [ "$1" -ge 1 ]; then
     service postfix condrestart || :
-    mta=`readlink /etc/alternatives/mta`
+    # don't use readlink as this is not available on rh73
+    mta=`[ -L /etc/alternatives/mta ] && ls -la /etc/alternatives/mta | awk '{ print $11 }'`
     if [ "$mta" = "%{sendmail_path}" ]; then
-        [ -x {_sbindir}/alternatives ] && \
-		{_sbindir}/alternatives --set mta %{sendmail_path}
+        {_sbindir}/alternatives --set mta %{sendmail_path}
     fi
 fi
 exit 0
@@ -1035,7 +973,7 @@ umask 022
 
 %attr(0755, root, root) %{_sysconfdir}/postfix/postfix-chroot.sh
 
-%attr(0755, root, root) %config %{init_directory}/postfix
+%attr(0755, root, root) %config %{initdir}/postfix
 
 %dir                      %verify(not md5 size mtime) %{_var}/spool/postfix
 
@@ -1125,6 +1063,7 @@ umask 022
 %{sendmail_path}
 %{mailq_path}
 %{newaliases_path}
+%{usrlib_sendmail}
 %attr(0755, root, root) %{rmail_path}
 %attr(0755, root, root) %{_bindir}/postfinger
 %attr(0755, root, root) %{_sbindir}/qshape
@@ -1139,6 +1078,13 @@ umask 022
 #
 
 %changelog
+
+* Tue Mar 21 2006 Simon J Mudd <sjmudd@pobox.com> 2.2.9-3
+  - use only chkconfig (/usr/sbin/alternatives) on supported packages.
+    This contrasts previous support for boxes which did not have this.
+    However as of rh7.3 and later chkconfig includes /usr/sbin/alternatives
+    so I can simplify the rpm.  Only gotcha to be aware of *may* be
+    old /usr/lib/sendmail "links", but they should be ok.
 
 * Mon Mar 20 2006 Simon J Mudd <sjmudd@pobox.com> 2.2.9-2
   - update vda patch to 2.2.9
