change to 2.3.2-1 and disable SPF

diff --git a/postfix.spec.in b/postfix.spec.in
--- a/postfix.spec.in
+++ b/postfix.spec.in
@@ -1,4 +1,4 @@
-# $Id: postfix.spec.in,v 2.304.6.8 2006/08/04 17:20:20 sjmudd Exp $
+# $Id: postfix.spec.in,v 2.304.6.9 2006/08/06 09:00:37 sjmudd Exp $
 #
 # File used to generate the distribution-specific postfix.spec file.
 # If you need to make changes to postfix.spec, make them to postfix.spec.in
@@ -95,7 +95,7 @@
 # If set to 1 if official version, 0 if snapshot
 %define official 1
 %define V_postfix 2.3.2
-%define rel 0.5__SUFFIX__
+%define rel 1__SUFFIX__
 %if %{official}
 %define V_tarball %{V_postfix}
 %define ftp_dir official
@@ -258,7 +258,7 @@ The binary and source rpms I produce are currently available at
 and the mirrors which can be found at the following URL:
 	http://postfix.WL0.org/en/mirrors/
 
-This package/specfile was built from postfix.spec.in $Revision: 2.304.6.8 $.
+This package/specfile was built from postfix.spec.in $Revision: 2.304.6.9 $.
 To see the build options used to build this package see the file %{_sysconfdir}/postfix/postfix.spec.cf
 
 To use postfix with alternative options download the source package and
@@ -343,6 +343,8 @@ sh dict_cdb.sh
 %endif
 
 %if %{with_spf}
+	echo "ERROR: The postfix-2.3 RPM does not yet support SPF, exiting"
+	exit 1
 if [ "%{with_spf}" -le 1 ]; then
 %patch7 -p1 -b .spf
 else
@@ -485,11 +487,12 @@ umask 022
     %{_sbindir}/useradd -d %{_var}/spool/postfix -s /bin/true -g postfix -G mail -M -r postfix
 }
 
-# If Postfix is not a member of the mail group (it wasn't in older versions of
-# my package) add it to the group.  This is needed for people using cyrus,
-# linked by unix sockets (amongst other things)
-GROUP=$(id postfix | awk '{print $3}' | sed -e 's/groups=//' | grep mail)
-test -z "${GROUP}" && usermod -G mail postfix || :
+# Add postfix user to the mail group.  This is needed for people using cyrus,
+# linked by unix sockets (amongst other things).
+test -z "$(id postfix | awk '{print $3}' | sed -e 's/groups=//' | grep mail)" && {
+    %whinge "Adding postfix user to mail group"
+    %{_sbindir}/usermod -G mail postfix
+}
 
 # check for a new install and see if a non package installed Postfix might
 # exist.  Attempt to avoid overwriting the source config and provide a warning.
@@ -1094,9 +1097,9 @@ umask 022
 
 %changelog
 
-* Tue Aug 04 2006 Simon J Mudd <sjmudd@pobox.com> 2.3.2-0.5
-  - check that each of the different options work ok (all seems ok except
-    libspf)
+* Sun Aug 06 2006 Simon J Mudd <sjmudd@pobox.com> 2.3.2-1
+  - check that each of the different options work ok
+    - all seems ok except libspf
   - adjust smtp_multiline_banner patch to work on 2.3.2
   - change compilation options for SASL
   - update Postfix to   2.3.2
